### ISSUE TITLE
make slides aware of viewport size, fix centering on large screens

### ISSUE THREAD

**Issue by seaofclouds** [nzoschke/gistdeck#4] opened 2012-06-22 23:11 UTC
- on large screens, the content is not centered vertically.
- the next slide is displayed rather than hidden.
- arrow keys do not work as expected.

<img src="http://dl.dropbox.com/u/2361730/Screenshots/kg.png" height="500">

**Comment by hakre** [comment] 2012-07-16 10:39
I can confirm this problem. Later-on keyboard navigation even does not work any longer, left and right keys for example, you can not go back to the start with the left key. Testing with chrome on windows XP with a display resolution of 1920x1200 in both a maximized browser window and in full-screen window (F11).

**Comment by henrahmagix** [comment] 2013-01-19 23:09
Fixed in #16 =)

**Comment by hakre** [comment] 2013-01-20 20:19
Is this already on the homepage? Because if I follow [the standard install / test](https://gistdeck.herokuapp.com/), it does not work at all (I can not confirm this fixed).

**Comment by henrahmagix** [comment] 2013-01-20 20:33
Sorry @hakre, by **fixed** I meant there's a fix available in pull-request #16. It's not on the homepage yet.

I have tried to get it working on [my own GitHub Page](http://henrahmagix.github.com/gistdeck) but I am running into issues. So currently, there isn't a way to get a working Gistdeck until we can serve the script and css from a server using **https**.

However, I have tested it to be working by other means =)

**Comment by hakre** [comment] 2013-01-20 20:49
Yes, just wanted to let you know that I wanted to just verify your tested (I find that often useful if bug-reporters confirm a fix, so I do that). Will do so when I'm able to run it. No idea why HTTPS is needed btw.

**Comment by henrahmagix** [comment] 2013-01-20 21:08
Ah ok, that's brilliant @hakre, great to know you want to test it! To test just the code itself, not the cross-domain issues, you can edit the bookmarklet and script to point to your **localhost server**. That's how I got it working =)

## Cross-domain issues

The two places I can source the script and css files are:
- `http://henrahmagix.github.com/gistdeck/`
- `https://raw.github.com/henrahmagix/gistdeck/add-to-gist-io`

GitHub's gist page are served **HTTPS**. That removes the first option since it is **HTTP** and the request gets blocked for not being secure.

The second option serves the files as `text/plain`. This seems to work fine (on occasion) for the script **but not for the css** as that needs to be served as `text/css`.

Therefore, I have no method of serving the updated files correctly at http://henrahmagix.github.com/gistdeck/.

## Styles are broken

Currently, Gistdeck won't work at all since GitHub updated the gist page template and styles. You will need the fix in #15. http://henrahmagix.github.com/gistdeck/ includes both fixes.

**Comment by nzoschke** [comment] 2013-02-23 23:07
Haven't tested this extensively but #16 is merged and released. Thanks henrahmagix!

**Closed as completed by nzoschke** 2013-02-23 23:07 UTC

**Comment by henrahmagix** [comment] 2013-02-24 20:40
You're welcome! =D
